name: terraform-destroy
description: Destroys all resources in a terraform workspace
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false
  variables:
    description: Variable definitions
    required: false
    deprecationMessage: Use the variables input instead.
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
  var_file:
    description: List of var file paths, one per line
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: 0

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:07cd443fbd4fc64bddf6901cfb1e6daff9f4b3935e68324bf40d395fb2ad6a7f
  entrypoint: /entrypoints/destroy.sh

branding:
  icon: globe
  color: purple
